name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker stop my-container || true
            docker rm my-container || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-image:latest
            docker run -d --name my-container -p 80:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/my-image:latest
